config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contacto', to: 'static_pages#contacto'
  get '/video', to: 'static_pages#video'
  get '/comprar', to: 'static_pages#comprar'
  root 'static_pages#home'
  resources :posts
  resources :articles
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
   validates :title, presence: true, length: { minimum: 5}
   validates :body, :image, presence: true
   has_one_attached :image
   extend FriendlyId
   friendly_id :title, use: :slugged
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
  has_one_attached :image
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    validates :body, :image, presence: true
    has_one_attached :image
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, inverse_of: :recipe
    has_many :directions, inverse_of: :recipe
    has_one_attached :image
    accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
    validates :title, :description, :image, presence: true
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :find_article, only:[:show, :edit, :update, :destroy]
    def index
        @articles =Article.all.order('created_at DESC')
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end
    
    def update
        if @article.update(params[:article].permit(:title, :body, :image))
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def edit
    end
    
    def destroy
        @article.destroy
        
        redirect_to articles_path
    end
    
    def show
    end
    
    private
        def article_params
            params.require(:article).permit(:title, :body, :image)
        end
        
        def find_article
            @article = Article.friendly.find(params[:id])
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :find_post, only: [:show, :edit, :update, :destroy]
 
  def index
    @posts = Post.all.order('created_at DESC')
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to @post, notice: "Success!"
    else
      render 'new'
    end
  end

  def update
    if @post.update(params[:post].permit(:title, :body, :image))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    
    redirect_to posts_path
  end

  def show
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
    
    def find_post
      @post = Post.friendly.find(params[:id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  
  def index
    @recipes = Recipe.all.order("created_at DESC")
  end
  
  def show
  end
   
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    
    if @recipe.save
      redirect_to @recipe, notice: "Success you created new recipe!"
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end
  
  def destroy
    @recipe.destroy
    redirect_to recipes_path, notice: "Successfully deleted"
  end
  
  private
  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, 
    ingredients_attributes: [:id, :name, :_destroy], 
    directions_attributes: [:id, :image, :step, :_destroy])
  end
  
  def find_recipe
    @recipe = Recipe.friendly.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.order("created_at desc").limit(3)
    @recipes =Recipe.order('created_at DESC').limit(2)
    @articles =Article.order('created_at DESC').limit(3).offset(3)
    @newarticles =Article.order('created_at DESC').limit(3)
    @bottomarticles =Article.order('created_at DESC').limit(1).offset(6)
  end

  def about
  end

  def contacto
  end

  def video
  end

  def comprar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<div class="container">
    <%= simple_form_for @article do |f| %>
        <% if @article.errors.any? %>
    <div>
        <h2>
            <%= pluralize(@article.errors.count, "error") %> prevented this post from saving</h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
            <% end %>
            </ul>
    </div>
        <% end %>
            <%= f.input :title, input_html: { class: 'form-control'} %>
            <%= f.input :body, input_html: { class: 'form-control'} %>
            <%= f.input :image, input_html: { class: 'form-control'} %>
            <%= f.submit 'Save' %>
    <% end %>
</div>

app/views/articles/edit.html.erb
<div class="container">
    <h1>Edit Article</h1>
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
    <% @articles.each do |article| %>
    <div>
        <h2 class="title"><%= link_to article.title, article %></h2>
        <p><%= article.created_at.strftime("%d . %m .  %Y") %></p>
    </div>
<% end %>
</div>

app/views/articles/new.html.erb
<div class="container">
    <h1>New article</h1>
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
    <%= image_tag(@article.image, style:'width:100%') if @article.image.attached? %>
    <h1><%= @article.title %></h1>
    <p><%= @article.created_at.strftime("%d . %m .  %Y") %>
        | <%= link_to 'Edit', edit_article_path(@article) %>
        | <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm:
        'Are you sure?'} %>
    </p>
    <p><%= @article.body %></p>
</div>

app/views/layouts/_header.html.erb
<header>
      <nav class="navbar navbar-dark bg-dark">
      <a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <h6 id="toggle-h6">Menu</h6>
      </a>
      <div class="navbar-collapse collapse" id="navbarsExample01" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        </ul>
      </div>
      </nav>
      <div class="nav justify-content-center" id="nav-logo">
          <%= link_to root_path do%>
            <%= image_tag "https://fuzati.com/wp-content/uploads/2016/12/Bootstrap-Logo.png" %>
         <% end %>
      </div>
      <ul class="nav justify-content-center" id="nav-2">
        <li class="nav-item">
          <a class="nav-link" href="#">Empieza aqui</a>
        </li>
        <li class="nav-item"><%= link_to "Recetas", recipes_path, :class => "nav-link" %></li>
        <li class="nav-item">
          <a class="nav-link" href="#">Baby Led Weaning</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Seguridad</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Nutricion</a>
        </li>
        <li class="nav-item"><%= link_to "Videos", video_path, :class => "nav-link"%></li>
        <li class="nav-item"><a class="nav-link" href="#">Crianza</a></li>
      </ul>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blw en Espanol</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
    <%= simple_form_for @post do |f| %>
        <% if @post.errors.any? %>
    <div>
        <h2>
            <%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
            <% end %>
            </ul>
    </div>
        <% end %>
            <%= f.input :title, input_html: { class: 'form-control'} %>
            <%= f.input :body, input_html: { class: 'form-control'} %>
            <%= f.input :image, input_html: { class: 'form-control'} %>
            <%= f.submit 'Save' %>
    <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div>
        <h2 class="title">
            <%= link_to post.title, post %>
        </h2>
        <p>
            <%= post.created_at.strftime("%d . %m .  %Y") %>
        </p>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
    <%= image_tag(@post.image, style:'width:100%') if @post.image.attached? %>
    <h1><%= @post.title %></h1>
    <p><%= @post.created_at.strftime("%d . %m .  %Y") %>
        | <%= link_to 'Edit', edit_article_path(@post) %>
        | <%= link_to 'Delete', article_path(@post), method: :delete, data: {confirm:
        'Are you sure?'} %>
    </p>
    <p><%= @post.body %></p>
</div>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: 'form-input form-control' } %>
    <%= f.input :image, input_html: {class: 'form-control'} %>
    <%= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<div class="panel-body">
<%= simple_form_for @recipe, html: {multipart: true} do |f| %>
    <% if @recipe.errors.any? %>
        <div>
            <h2><%= pluralize(@recipe.errors.count, "error") %> prevented this post from saving</h2>
            <ul>
                <% @recipe.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
      <%= f.input :title, input_html: { class: 'form-control'} %>
      <%= f.input :image, input_html: {class: 'form-control'} %>
        <%= f.input :description, input_html: { class: 'form-control'} %>
      <div class="row">
        <div class="col-md-6">
            <h3>Ingredients</h3>
            <div id="ingredients">
              <%= f.simple_fields_for :ingredients do |ingredient| %>
                <%= render 'ingredient_fields', :f => ingredient %>
              <% end %>
              <div class='links'>
                <%= link_to_add_association 'Add Ingredient', f, :ingredients %>
              </div>
            </div>
          </div>
        <div class="col-md-6">
          <h3>Directions</h3>
          <div id="directions">
            <%= f.simple_fields_for :directions do |direction| %>
              <%= render 'direction_fields', :f => direction %>
            <% end %>
            <div class="links">
              <%= link_to_add_association 'Add Step', f, :directions %>
            </div>
          </div>
        </div>
    </div>
      <%= f.submit 'Save' %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class='nested-fields'>
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit recipe</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
    <div>
        <h2 class="title">
            <%= link_to recipe.title, recipe %>
        </h2>
        <p>
            <%= recipe.created_at.strftime("%d . %m .  %Y") %>
        </p>
    </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>
<br>
<%= link_to "All recipes", recipes_path %>

app/views/recipes/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      <%= @recipe.title %>
    </h1>
  </div>
  <div class="col-md-9" id="recipe-top">
    <%= image_tag(@recipe.image, style:'width:100%') %>
      <p class="description">
        <%= @recipe.description %>
      </p>
      <h2>Directions</h2>
      <ul>
        <% @recipe.directions.each do |direction| %>
          <li>
                  <% if direction.image %>
             <%= image_tag(direction.image, style:'width:100%')  %>
            <% end %>
            <%= direction.step %>
          </li>
        <% end %>
      </ul>
  </div>
  <div class="col-md-3">
    <%= image_tag(@recipe.image, style:'width:100%') %>
    <h2>
      <%= @recipe.title %>
    </h2>
    <div id="ingredients">
      <h2>Ingredients</h2>
      <ul>
        <% @recipe.ingredients.each do |ingredient| %>
          <li>
            <%= ingredient.name %>
          </li>
        <% end %>
      </ul>
    </div>
    <div id="directions">
      <h2>Directions</h2>
      <ul>
        <% @recipe.directions.each do |direction| %>
          <li>
      
            <%= direction.step %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

</div>
<div class="row">
  <div class="col-md-12">
    <%= link_to "Back", recipes_path(@recipe) %>
    <%= link_to "Edit", edit_recipe_path(@recipe) %>
    <%= link_to "Delete", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure?" }, :class => "btn btn-default" %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/comprar.html.erb
<h1>StaticPages#comprar</h1>
<p>Find me in app/views/static_pages/comprar.html.erb</p>

app/views/static_pages/contacto.html.erb
<h1>StaticPages#contacto</h1>
<p>Find me in app/views/static_pages/contacto.html.erb</p>

app/views/static_pages/home.html.erb
<!-- CAROUSEL -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <% @newarticles.each.with_index(0) do |article, index| %>
          <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>">
          </li>
        <% end %>
      </ol>
      <div class="carousel-inner">
        <% @newarticles.each.with_index(0) do |article, index| %>
        <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
          <%= link_to image_tag(article.image, class: "img-fluid") if article.image.attached? %>
          <div class="container">
            <div class="carousel-caption text-left">
              <h1>
                <%= link_to article.title, article %>
              </h1>
              <!--p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p-->
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
<!-- MAIN CONTENT AFTER CARROUSEL -->
<div class="container">
<!-- 3 ARTICLES IN ROW  -->
  <% @articles.each_slice(3) do |article| %>
  <div class="card-deck posts">
    <% article.each do |article| %>
    <div class="card">
      <%= link_to image_tag(article.image, class: "img-fluid") if article.image.attached? %>      
      <div class="card-body">
        <h2>Article Category</h2>
        <h3 class="card-title">
          <%= link_to article.title, article %>
        </h3>
        <p class="card-text">
          <%= article.created_at.strftime("%d.%m.%Y") %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
<!-- 2 RECIPES IN ROW  -->
  <% @recipes.each_slice(2) do |recipe| %>
  <div class="card-deck posts">
    <% recipe.each do |recipe| %>
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h2>Recipe Category</h2>
        <h3 class="card-title">
          <%= link_to recipe.title, recipe %>
        </h3>
        <p class="card-text">
          <%= recipe.created_at.strftime("%d.%m.%Y") %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
<!-- 3 POSTS IN ROW BLOG  -->
  <% @posts.each_slice(3)  do |post| %>
  <div class="card-deck posts">
    <% post.each do |post| %>
    <div class="card">
      <%= link_to image_tag(post.image, class: "img-fluid") if post.image.attached? %>
      <div class="card-body">
        <h2>Posts Category</h2>
        <h3 class="card-title">
          <%= link_to post.title, post %>
        </h3>
        <p class="card-text">
          <%= post.created_at.strftime("%d.%m.%Y") %>        
        </p>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
    <!-- 1 POST IN ROW ARTICLE -->
  <% @bottomarticles.each_slice(1) do |article| %>
  <div class="card-deck posts">
    <% article.each do |article| %>
    <div class="card">
      <%= link_to image_tag(article.image, class: "img-fluid") if article.image.attached? %>      
      <div class="card-body">
        <h2>Article Category</h2>
        <h3 class="card-title">
          <%= link_to article.title, article %>
        </h3>
        <p class="card-text">
          <%= article.created_at.strftime("%d.%m.%Y") %>        
        </p>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>

<!--<p><.%= link_to post.body.truncate_words(35), post%></p>-->

<script type="text/javascript">
  $(document).on('turbolinks:load', function(){
     $('.carousel').carousel({
        interval: 2000
     });
  });
</script>

app/views/static_pages/video.html.erb
<h1>StaticPages#video</h1>
<p>Find me in app/views/static_pages/video.html.erb</p>